### ISSUE TITLE
source code? open source?

### ISSUE THREAD

**Issue by jrochkind** [ViDA-NYU/ARIES-Issues#12]
Hi, the press release at "https://engineering.nyu.edu/news/new-digital-platform-nyu-tandon-and-frick-collection-brings-art-history-research-digital-age" says "New Open-Source Software". 

Is this correct, this software is open source?  

I found a link to this github project in the footer at https://artimageexplorationspace.com/, but of course this is called 'ARIES-Issues' and doesn't actually have the source code. 

Is the source code available?  I am also curious what platform(s) it is written in. Thanks!

**Comment by mlage** [comment]
Hi @jrochkind,

Thanks for your interest in ARIES.

We are developing ARIES with the goal of making it open source, but right now we're still improving the code, and we plan to release it in the near future. 

Also, ARIES is developed using Angular.

Thanks!
