### ISSUE TITLE
How do you put in diacriticals in the metadata, like accents in french or umlauts in German?

### ISSUE THREAD

**Issue by Lwoodruby** [ViDA-NYU/ARIES-Issues#7]

**Comment by Lhaylla** [comment]
Hi Louisa, I'm attaching a print with some diacritics I put in the metadata. Are these you are trying to use? 

![screen shot 2018-06-25 at 10 00 06 am](https://user-images.githubusercontent.com/10701963/41854792-15153156-785f-11e8-8afc-aaa70ab456e3.png)

**Comment by Lwoodruby** [comment]
Yes.

**Comment by Lhaylla** [comment]
I typed on ARIES like I type on Word using the keyboard shortcuts. Try to do the same and let me know if you got it.

**Comment by Lwoodruby** [comment]
Ok.  Yesterday the problem was I was on a Mac.  I think that is part of my problem on weekends!  The metadata I put in yesterday also held, which is good.  I will look again at home on the Mac and see if somehow its not saving there….
